#!/usr/bin/env python3
"""Generate docs/COMMANDS.md from the manifests.

A hand-written command reference for 80 commands would be wrong within a week — the same
argument that makes the commands themselves generated. This reads the manifests, so the
reference and the CLI cannot disagree.

Usage::

    python3 tools/generate_docs.py            # write docs/COMMANDS.md
    python3 tools/generate_docs.py --check    # fail if it is out of date
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST_DIR = ROOT / "cli-manifest"
TARGET = ROOT / "docs" / "COMMANDS.md"

HEADER = """<!-- Generated by tools/generate_docs.py. Do not edit; change the manifests. -->

# Command reference

Every generated command, with the OSDU operation behind it. `osducs <noun> --help` shows the
same information at the terminal, and is the authority if the two ever disagree.

Commands are named for the **resource**, not the service that hosts it, so verbs live under
the thing they act on: searching records is `osducs record search`. See
[COMMAND-GRAMMAR.md](../COMMAND-GRAMMAR.md) for why.

Hand-written commands — `osducs status`, `osducs completion` — are not listed here; they have
no manifest. Run `osducs --help` for the full tree.

"""


def load() -> dict[str, list[dict]]:
    """Commands grouped by their top-level noun."""
    grouped: dict[str, list[dict]] = {}
    for path in sorted(MANIFEST_DIR.glob("*.yaml")):
        manifest = yaml.safe_load(path.read_text(encoding="utf-8"))
        for command in manifest.get("commands") or []:
            noun = command["command"].split()[0]
            grouped.setdefault(noun, []).append({**command, "_service": manifest["service"]})
    return dict(sorted(grouped.items()))


def options(command: dict) -> list[tuple[str, str, bool]]:
    """Every flag a command accepts, as (flags, help, required)."""
    found = []
    for config in (command.get("params") or {}).values():
        found.append((flags(config), (config.get("help") or "").strip(),
                      bool(config.get("required"))))
    body = command.get("body") or {}
    for config in (body.get("fields") or {}).values():
        found.append((flags(config), (config.get("help") or "").strip(),
                      bool(config.get("required"))))
    if body.get("flag") and not body.get("fields"):
        found.append((flags(body), (body.get("help") or "").strip(),
                      bool(body.get("required", True))))
    return found


def flags(config: dict) -> str:
    return ", ".join(f"`{f}`" for f in (config.get("short"), config.get("flag")) if f)


def rules(command: dict) -> list[str]:
    """Constraints the CLI enforces before sending anything."""
    stated = []
    if one_of := command.get("require-one-of"):
        stated.append("One of " + " or ".join(
            f"`{(command['params'][name]).get('flag')}`" for name in one_of) + " is required.")
    raw = command.get("mutually-exclusive") or []
    groups = raw if raw and isinstance(raw[0], list) else ([raw] if raw else [])
    lookup = {**(command.get("params") or {}), **((command.get("body") or {}).get("fields") or {})}
    for group in groups:
        stated.append(" and ".join(f"`{lookup[name].get('flag')}`" for name in group)
                      + " cannot be combined.")
    return stated


def render() -> str:
    grouped = load()
    out = [HEADER]

    out.append("| Noun | Commands |")
    out.append("|---|---|")
    for noun, commands in grouped.items():
        verbs = ", ".join(f"`{c['command'].split(maxsplit=1)[1]}`" for c in commands)
        out.append(f"| [`{noun}`](#{noun}) | {verbs} |")
    out.append("")

    for noun, commands in grouped.items():
        out.append(f"## {noun}\n")
        for command in sorted(commands, key=lambda c: c["command"]):
            out.append(f"### `osducs {command['command']}`\n")
            if summary := command.get("summary"):
                out.append(f"{summary}\n")
            operation = command["op"]
            out.append(f"`{operation['method'].upper()} {operation['path']}` "
                       f"— {command['_service']}\n")

            if flags_found := options(command):
                out.append("| Option | Required | Description |")
                out.append("|---|---|---|")
                for names, help_text, required in flags_found:
                    text = " ".join(help_text.split()) or "—"
                    out.append(f"| {names} | {'yes' if required else ''} | {text} |")
                out.append("")

            for rule in rules(command):
                out.append(f"> {rule}\n")

            examples = command.get("examples") or []
            if examples:
                out.append("```bash")
                for example in examples:
                    args = example["args"] if isinstance(example, dict) else example
                    out.append(f"osducs {command['command']} {str(args).strip()}")
                out.append("```\n")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the file on disk is out of date")
    args = parser.parse_args()

    produced = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != produced:
            print(f"{TARGET.relative_to(ROOT)} is out of date. "
                  f"Run python3 tools/generate_docs.py", file=sys.stderr)
            return 1
        print(f"{TARGET.relative_to(ROOT)} is up to date.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(produced, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} "
          f"({len(load())} nouns, {sum(len(v) for v in load().values())} commands)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
